### ISSUE TITLE
Why is setDrawingCacheEnabled true?

### ISSUE THREAD

**Issue by shaharyakir** [christophesmet/android_maskable_layout#10]
I was using a container which had two MaskableFrameLayouts. That container is animated as a popup when opening it. 

The animation was laggy, especially when other UI work was happening, such as showing images in the popup. 

I noticed that turning setDrawingCacheEnabled off dramatically improved the performance. 

Is there a reason it is turned on? 

If not I can make a pull request. 

Thanks

**Comment by christophesmet** [comment]
Mmh can't exactly remember.
Perhaps with some lower api issues I tested.
You are free to make a pull request and I'll retest it over here :)
Thanks ! 👍
