### ISSUE TITLE
Copyright notice missing

### ISSUE THREAD

**Issue by etanhatch** [christophesmet/android_maskable_layout#12]
In order to properly use a library with an Apache license, a copyright notice like "Copyright (C) 201x-2017 Christophe Smet" is required. Could you add this with the license in the README.md?

**Comment by christophesmet** [comment]
Does d51245736aea0c3482c8ba28a6751e4e49de3168 work for you ?

**Comment by etanhatch** [comment]
Yes that's perfect!
