### ISSUE TITLE
Out of memory issue

### ISSUE THREAD

**Issue by nitishhhh3** [christophesmet/android_maskable_layout#16]
I am facing out of memory issue on carsh report in huge ammount -

java.lang.OutOfMemoryError: Failed to allocate a 4170132 byte allocation with 3545088 free bytes and 3MB until OOM
--
1	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
2	at android.graphics.Bitmap.nativeCreate(Native Method)
3	at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
4	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
5	at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
6	at com.christophesmet.android.views.maskableframelayout.MaskableFrameLayout.android.graphics.Bitmap makeBitmapMask(android.graphics.drawable.Drawable)(MaskableFrameLayout.java:151)
7	at com.christophesmet.android.views.maskableframelayout.MaskableFrameLayout.access$200(MaskableFrameLayout.java:29)
8	at com.christophesmet.android.views.maskableframelayout.MaskableFrameLayout$1.void onGlobalLayout()(MaskableFrameLayout.java:233)
9	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:982)
10	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2410)
11	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
12	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
13	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
14	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
15	at android.view.Choreographer.doFrame(Choreographer.java:631)
16	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
17	at android.os.Handler.handleCallback(Handler.java:739)
18	at android.os.Handler.dispatchMessage(Handler.java:95)
19	at android.os.Looper.loop(Looper.java:158)

**Comment by christophesmet** [comment]
Its running out of memory since it needs to create a new bitmap masked from your original view.
So either lower the memory pressure of the view you are masking. Ex use different bitmap config, without alpha or a lower amount of colors/ bits available.
Or if you are doing memory intensive image masking, then you need to use a shader.

**Comment by angelmarrugo** [comment]
I don't think the solution is clear, could you explain a little more detailed?
