### ISSUE TITLE
Repo not found or no access token provided

### ISSUE THREAD

**Issue by avioraboo** [christophesmet/android_maskable_layout#17]
Hello,
After clicking on the JitPack link: "https://jitpack.io/#christophesmet/android_maskable_layout" 
I'm getting this text:
"Repo not found or no access token provided".

Also in my project, it says: "Error:(125, 13) Failed to resolve: com.github.christophesmet:android_maskable_layout:-SNAPSHOT".

**Comment by ZhouJialei** [comment]
+1

**Comment by christophesmet** [comment]
Jitpack updated their artifact providing.
They give timeouts and appeared to be down for a while.
Try this: 
repositories {
    maven { url 'https://jitpack.io' }
}
dependencies {
    compile 'com.github.christophesmet:android_maskable_layout:v1.0.0'
}

Tried and tested it, this should work :)

**Comment by ZhouJialei** [comment]
I've tried and got no luck. gradle console output:
   > Could not resolve com.github.christophesmet:android_maskable_layout:v1.0.0.
      > Could not get resource 'https://jitpack.io/com/github/christophesmet/android_maskable_layout/v1.0.0/android_maskable_layout-v1.0.0.pom'.
         > Could not GET 'https://jitpack.io/com/github/christophesmet/android_maskable_layout/v1.0.0/android_maskable_layout-v1.0.0.pom'.
            > Connect to 127.0.0.1:64873 [/127.0.0.1] failed: Connection refused (Connection refused)
Any idea @christophesmet ?

**Comment by christophesmet** [comment]
Seems like an issue on your end. The dependency is available online, so it has something to do with your internet connection.
Closed: Jitpack has been updated, connection refused on clients end.
