### ISSUE TITLE
BUG for mask area

### ISSUE THREAD

**Issue by leaf918** [christophesmet/android_maskable_layout#3]
in function makeBitmapMask:
Canvas canvas = new Canvas(mask);
                drawable.setBounds(0, 0, getMeasuredWidth(), getMeasuredWidth());
as above:
the last line should be: drawable.setBounds(0, 0, getMeasuredWidth(), getMeasuredHeight());

you made a typo.

**Comment by christophesmet** [comment]
Thanks for spotting that !
Fixed and closed.
Thanks again !
