### ISSUE TITLE
support for Vector Drawable

### ISSUE THREAD

**Issue by mojtaba-yekta** [christophesmet/android_maskable_layout#33]
Hi, in api level 18 when set a vector drawable to "mask" attribute I get this error:

`... android.content.res.Resources$NotFoundException: File {address to resource} from drawable resource ...`

the problem was from this function:

```
//Mask functions
@Nullable
private Drawable loadMask(TypedArray a) {
    return a.getDrawable(R.styleable.MaskableLayout_mask);
}
```

I found a solution [here ](https://stackoverflow.com/questions/42863198/how-do-you-get-a-drawable-object-via-a-typedarray-when-the-drawable-resource-is) and by using AppCompatResources solved my problem.

I changed loadMask to this:

   ```
 //Mask functions
    @Nullable
    private Drawable loadMask(TypedArray a) {
        final int drawableResId = a.getResourceId(R.styleable.MaskableLayout_mask, -1);
        return AppCompatResources.getDrawable(getContext(), drawableResId);
    }
```

**Comment by christophesmet** [comment]
Hi there,
That could indeed be the case, I never tested vector drawables. 
Looks like a good solution!
Could you make this into a pullrequest ?
Currently traveling, but I'll approve it and merge it when created. 
Thanks for the report and work!

**Comment by mojtaba-yekta** [comment]
Sure
I made the pullrequest right now

**Comment by christophesmet** [comment]
Merged. Thanks!
