### ISSUE TITLE
Use B&W Mask

### ISSUE THREAD

**Issue by dacastro4** [christophesmet/android_maskable_layout#37]
Hey! I just need some help because I'm trying to use a mask that is a JPEG file that has white background and the mask part is black. It kinda works but how can I change the color of the mask? I tried applying `backgroundTint` but It didn't work.
This is what I have.
```
<com.christophesmet.android.views.maskableframelayout.MaskableFrameLayout
            android:id="@+id/car_bg_base_mask"
            app:porterduffxfermode="OVERLAY"
            app:mask="@drawable/m3_overlay"
            android:elevation="-1dp"
            android:backgroundTint="@color/blue"
            android:layout_height="match_parent"
            android:layout_width="match_parent">

            <ImageView
                android:id="@+id/car_bg_base"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:contentDescription="@string/car_background"/>

        </com.christophesmet.android.views.maskableframelayout.MaskableFrameLayout>
```

**Comment by christophesmet** [comment]
Why would you want to colour the mask?
Could you provide an image of the result you are trying to achieve?
I'm not sure what the end goal is.

**Comment by dacastro4** [comment]
To change the color of the image. 
Sure:
Having this image: 
![image](https://user-images.githubusercontent.com/7808930/51491506-84a3fa80-1d7c-11e9-8877-7229673b214a.png)
and this mask: 
![mask](https://user-images.githubusercontent.com/7808930/51491516-8cfc3580-1d7c-11e9-9d5d-b11cf4b5e211.png)
result:  ![result](https://user-images.githubusercontent.com/7808930/51491526-95547080-1d7c-11e9-8a24-cdb9da22fb60.jpg)

I can accomplish this on Affinity Designer by adding color to the mask but I have to do it programatically because the masks and the colors change.

**Comment by christophesmet** [comment]
I think in order for this to work you have to color your mask.
Give the color pixels an alpha of 255 and the transparent ones an alpha of 0.
Then it should be properly masked.
I really think you need to color your mask.

**Comment by dacastro4** [comment]
@christophesmet no, I don't have a sample project. I'm gonna try painting the mask before.
