### ISSUE TITLE
Missing break

### ISSUE THREAD

**Issue by spidfire** [christophesmet/android_maskable_layout#39]
https://github.com/christophesmet/android_maskable_layout/blob/cfa04d0713cedb01383fc3b7a42e46769ba22906/library/src/main/java/com/christophesmet/android/views/maskableframelayout/MaskableFrameLayout.java#L319

I converted it to kotlin and it gave a overwrite error so I though I mention it :)

**Comment by spidfire** [comment]
And same with  MODE_ADD

**Comment by christophesmet** [comment]
Thanks for letting me know :)
Would you want to create a PR for that Kotlin conversion?
It's been on the back of my mind for a long time and I want to add some tests for the xml parsing.
It would be a great help if you would :)

**Comment by minhnhattonthat** [comment]
#47 fixed this :)

**Comment by christophesmet** [comment]
Thanks again!
