### ISSUE TITLE
Doesn't seem to work with a nested map fragment

### ISSUE THREAD

**Issue by GYberkeley** [christophesmet/android_maskable_layout#5]
<com.christophesmet.android.views.maskableframelayout.MaskableFrameLayout
            android:id="@+id/maskable_frame_layout"
            android:layout_width="200dp"
            android:layout_height="200dp"
            android:layout_centerHorizontal="true"
            android:layout_centerVertical="true"
            android:layout_below="@id/spacer_between_logo_and_map"
            app:porterduffxfermode="DST_IN"
            app:mask="@drawable/circle">

            <fragment xmlns:android="http://schemas.android.com/apk/res/android"
                android:id="@+id/map"
                android:transitionName="@string/map"
                android:layout_width="200dp"
                android:layout_height="200dp"
                tools:context="com.example.gyang.android.MapActivity"
                class="com.google.android.gms.maps.SupportMapFragment"/>

        </com.christophesmet.android.views.maskableframelayout.MaskableFrameLayout>

Any ideas?

**Comment by christophesmet** [comment]
Yes, id does work with fragment.
But the fragment you are using is the support map fragment.
This maksing only works for software layers.
The map fragment is rendered by the hardware.
So those two will never work.
Either use shaders, or don't use a hardware rendered view.

**Comment by GYberkeley** [comment]
Ah I see. I didn't need to that it was rendered by the hardware. That's a shame :(
