### ISSUE TITLE
Use mask layout programmatically

### ISSUE THREAD

**Issue by marwanzak** [christophesmet/android_maskable_layout#6]
How to set mask to layout programmatically no only in xml?.

**Comment by chazhenry** [comment]
Yes, would love to apply a mask programmatically as well as turn on/off showing the full image behind.

**Comment by christophesmet** [comment]
You can change the mask with the function setMask();

**Comment by chazhenry** [comment]
Partly. If I understand, you could declare a MaskableFrameLayout and then using the overloaded setMask method, give it a drawable to mask. How would you 'unset' it and let the original view show through? I tried setMask(null) and setMask(0). Both seem to just log the exception. Thanks for putting this component out there. Very useful in my app.

**Comment by christophesmet** [comment]
Ah, yes. That is true.
You can either add an enabled state.
Or make it possible to add the mask as a bitmap.
If the bitmap mask is null. It should just draw it without any masking.
I would suggest keeping a boolean "mEnabled" and toggling it.
In the dispatchDraw then check it.
Feel free to submit a pull request :)
I'm looking forward to it !

**Comment by chazhenry** [comment]
I did some testing but unfortunately the mask won't work for VideoView. I'm trying to have two masks that create a two video horizontal split-screen effect [ A | B ] and to slide a video behind each mask. I created a simple test case which works for images but it has no masking effect on ViewView. Is that a known limitation?

**Comment by christophesmet** [comment]
The VideoView is backed by the hardware.
This only works for software layers.
If you want to use hardware layer then use shaders.
This is not a bug, and will never be possible.
